### ISSUE TITLE
how to get dataset?

### ISSUE THREAD

**Issue by yueyemijing** [BorisLestsov/cudnn_coursework#1]
when I run "python make_dataset.py"  cmd, I get this error prin:
No such file or directory: 'annotations/instances_train2014.json'

how to fix it?

**Comment by BorisLestsov** [comment]
Hi. This repo works only with MS COCO dataset for now. You need to download JSON annotation file and images themselves from http://cocodataset.org/dataset.htm#download . You will need to create the directory "annotations" in the "dataset" folder, and put the JSON file with annotations there. Also you need to extract images from MS COCO to "dataset/pic/train" folder.
Alternatively you can mannually set all the paths in the main() function in make_dataset.py if you want to work with your own paths.
If you need to work with another dataset, you will need to rewrite the script "make_dataset.py", it should not be difficult, just make sure that post-processed data in the generated binary files is in the right format.

**Comment by yueyemijing** [comment]
thx very much!
